language: python
cache:
  pip: true
  directories:
    - .eggs
python:
  - 3.6
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.11.5
  - DJANGO_VERSION=2.0.1
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e git+https://github.com/nickromano/leather.git#egg=leather
  - pip install CairoSVG==2.1.2
  - pip install mock==2.0.0
  - pip install premailer==3.1.1
  - pip install flake8
  - pip install pytz
  - pip install coveralls
before_script:
  - flake8 .
script: coverage run setup.py test
after_success:
  - coveralls
